### ISSUE TITLE
NameError: name 'unicode' is not defined (python 3.4.3)

### ISSUE THREAD

**Issue by erikwt** [Stupeflix/freeze-requirements#8]
After a fresh install (pip install freeze-requirements) on python 3.4.3, I get the following error running freeze-requirements:
```
$ freeze-requirements
Traceback (most recent call last):
  File "/env3/bin/freeze-requirements", line 7, in <module>
    from freezerequirements.cli import main
  File "/env3/lib/python3.4/site-packages/freezerequirements/cli.py", line 14, in <module>
    from .utils import (likely_distro, cache_dir, cache_path,
  File "/env3/lib/python3.4/site-packages/freezerequirements/utils.py", line 139, in <module>
    class StringWithAttrs(unicode):
NameError: name 'unicode' is not defined
```
Is freeze-requirements supposed to support python 3.4.3?

**Comment by flupke** [comment]
Sorry freeze-requirements does not support python 3.
